---
- name: Install Apache, MySQL, Nginx on web server
  hosts: web
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - apache2
          - mysql-server
          - nginx
        state: present
        update_cache: yes

