---
- name: Install Apache, MySQL, Nginx on web server
  hosts: web
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache, MySQL, Nginx
      apt:
        name:
          - apache2
          - mysql-server
          - nginx
        state: present
